name: voguevoyage
description: A Flutter project with python flask API for YOLOv8 image classification model to suggest complementary clothing recommendations 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.2.7
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.13.6
  fluttertoast: ^8.2.4
  camera: ^0.10.5+7
  crypto: ^3.0.3
  image: ^4.0.15
  palette_generator: ^0.3.3+3
  csv: ^5.1.1
  scroll_snap_list: ^0.9.1
  tflite_flutter: ^0.10.4
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  flutter_vision: ^1.1.4
  http: ^1.0.0
  permission_handler: ^11.2.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.7

flutter:  
  assets:
    - assets/vv5_float32.tflite
    - assets/labels.txt
    - assets/images/dataset/
    - assets/images/
  fonts:
    - family: Satify
      fonts: 
        - asset: assets/Satisfy/Satisfy-Regular.ttf


  uses-material-design: true
